export const operationsTranslations = {
  tr: {
    adminOperations: {
      common: {
        liveOperation: 'CANLI OPERASYON', breakfastOperation: 'KAHVALTI OPERASYONU', refresh: 'Yenile', processing: 'İşleniyor...', delivered: 'Teslim edildi', cancel: 'Vazgeç', save: 'Kaydet', room: 'Oda', roomValue: 'Oda {{number}}', roomUpper: 'ODA', internalAccount: 'DAHİLİ HESAP', noGuestNote: 'Misafir notu belirtilmedi.', note: 'NOT', person: 'kişi', cash: 'Nakit', card: 'Kredi Kartı', own: 'OWN', optional: 'Opsiyonel',
      },
      orders: {
        title: 'Bekleyen siparişler', subtitle: 'Misafirlerden gelen siparişler oda numarasına göre listelenir.', loading: 'Siparişler yükleniyor...', refreshed: 'Sipariş listesi yenilendi.', loadError: 'Siparişler getirilemedi.', newItems: '{{count}} yeni sipariş geldi.', deliveredToast: '{{room}} siparişi teslim edildi.', deliverError: 'Teslim işlemi tamamlanamadı.', cancelAction: 'İptal et', cancelledToast: '{{room}} siparişi iptal edildi.', cancelError: 'Sipariş iptal edilemedi.', emptyTitle: 'Bekleyen sipariş yok', emptyBody: 'Yeni siparişler geldiğinde burada görünecek.', closeDialog: 'Pencereyi kapat', cancelEyebrow: 'SİPARİŞ İPTALİ', cancelTitle: '{{room}} siparişi iptal edilsin mi?', cancelWarning: 'Bu işlem geri alınamaz; sipariş yalnızca iptal kaydı olarak saklanır.', cancelling: 'İptal ediliyor...', confirmCancel: 'Siparişi iptal et',
      },
      breakfast: {
        title: 'Bugünün kahvaltıları', subtitle: "14:00'e kadar teslim edilmeyen kayıtlar otomatik iptal edilir.", loading: 'Kahvaltılar yükleniyor...', refreshed: 'Kahvaltı listesi yenilendi.', loadError: 'Kahvaltı listesi getirilemedi.', newItems: '{{count}} yeni kahvaltı kaydı geldi.', deliveredToast: 'Oda {{room}} kahvaltısı teslim edildi.', deliverError: 'Teslim işlemi tamamlanamadı.', updated: 'Kahvaltı bilgileri güncellendi.', updateError: 'Kahvaltı güncellenemedi.', edit: 'Düzenle', roomNumber: 'Oda numarası', guestCount: 'Kişi sayısı', requestedTime: 'Talep saati', breakfastDate: 'Kahvaltı tarihi', emptyTitle: 'Bugün için bekleyen kahvaltı yok', emptyBody: 'Planlanan kahvaltılar günü geldiğinde burada görünür.',
      },
      createBreakfast: {
        title: 'Kahvaltı planı oluştur', subtitle: 'Bugün veya ertesi gün ile başlayın; konaklama gün sayısı kadar kayıt otomatik oluşturulur.', roomRequired: 'Oda numarası zorunludur.', created: '{{count}} günlük kahvaltı planı oluşturuldu.', createError: 'Kahvaltı kaydı oluşturulamadı.', roomNumber: 'Oda numarası', roomPlaceholder: 'Örn. 203', guestCount: 'Kişi sayısı', requestedTime: 'Talep edilen saat', startDate: 'Başlangıç tarihi', breakfastDays: 'Kahvaltı günü', help: 'Örneğin 4 gün seçildiğinde, her gün için ayrı kahvaltı kaydı hazırlanır ve yalnızca o gün aktif listede görünür.', guestNote: 'Misafir notu', notePlaceholder: 'Örn. Laktozsuz süt', saving: 'Kaydediliyor...', submit: 'Kahvaltı planını oluştur',
      },
      dashboard: {
        eyebrow: 'KASA & RAPORLAR', title: 'Kasa görünümü', subtitle: 'OWN siparişleri kasa gelirinden ayrılarak ayrı bakiyede tutulur.', filtersLabel: 'Rapor filtreleri', periods: { day: 'Günlük', week: 'Haftalık', month: 'Aylık', custom: 'Özel aralık' }, month: 'Ay', day: 'Gün', weekDay: 'Haftanın günü', start: 'Başlangıç', end: 'Bitiş', loading: 'Kasa verileri yükleniyor...', loadError: 'Kasa verileri getirilemedi.', deliveredOrders: 'Teslim edilen sipariş', revenue: 'Toplam ciro', cost: 'Toplam maliyet', profit: 'Net kâr', ownBalance: 'OWN bakiyesi', ownMeta: '{{count}} OWN siparişi · gelir dışı', historyTitle: 'Filtrelenmiş sipariş geçmişi', historyNote: 'Geçmiş kayıtları silinmez', table: { room: 'Oda', products: 'Ürünler', payment: 'Ödeme', amount: 'Tutar', deliveredAt: 'Teslim zamanı' }, emptyHistory: 'Bu tarih aralığında teslim edilmiş sipariş yok.',
      },
    },
  },
  en: {
    adminOperations: {
      common: { liveOperation: 'LIVE OPERATIONS', breakfastOperation: 'BREAKFAST OPERATIONS', refresh: 'Refresh', processing: 'Processing...', delivered: 'Delivered', cancel: 'Cancel', save: 'Save', room: 'Room', roomValue: 'Room {{number}}', roomUpper: 'ROOM', internalAccount: 'INTERNAL ACCOUNT', noGuestNote: 'No guest note was provided.', note: 'NOTE', person: 'guests', cash: 'Cash', card: 'Credit Card', own: 'OWN', optional: 'Optional' },
      orders: { title: 'Pending orders', subtitle: 'Guest orders are listed by room number.', loading: 'Loading orders...', refreshed: 'Order list refreshed.', loadError: 'Orders could not be loaded.', newItems: '{{count}} new order(s) received.', deliveredToast: '{{room}} order delivered.', deliverError: 'Delivery could not be completed.', cancelAction: 'Cancel', cancelledToast: '{{room}} order cancelled.', cancelError: 'Order could not be cancelled.', emptyTitle: 'No pending orders', emptyBody: 'New orders will appear here.', closeDialog: 'Close dialog', cancelEyebrow: 'CANCEL ORDER', cancelTitle: 'Cancel the order for {{room}}?', cancelWarning: 'This action cannot be undone; the order will remain only as a cancellation record.', cancelling: 'Cancelling...', confirmCancel: 'Cancel order' },
      breakfast: { title: "Today's breakfasts", subtitle: 'Records not delivered by 14:00 are cancelled automatically.', loading: 'Loading breakfasts...', refreshed: 'Breakfast list refreshed.', loadError: 'Breakfast list could not be loaded.', newItems: '{{count}} new breakfast record(s) received.', deliveredToast: 'Breakfast for room {{room}} delivered.', deliverError: 'Delivery could not be completed.', updated: 'Breakfast details updated.', updateError: 'Breakfast could not be updated.', edit: 'Edit', roomNumber: 'Room number', guestCount: 'Guest count', requestedTime: 'Requested time', breakfastDate: 'Breakfast date', emptyTitle: 'No breakfasts pending today', emptyBody: 'Scheduled breakfasts will appear here on their service day.' },
      createBreakfast: { title: 'Create a breakfast plan', subtitle: 'Start today or tomorrow; one record is created for each stay day.', roomRequired: 'Room number is required.', created: '{{count}}-day breakfast plan created.', createError: 'Breakfast record could not be created.', roomNumber: 'Room number', roomPlaceholder: 'e.g. 203', guestCount: 'Guest count', requestedTime: 'Requested time', startDate: 'Start date', breakfastDays: 'Breakfast days', help: 'For example, selecting 4 days creates a separate record for every day, visible only on its service day.', guestNote: 'Guest note', notePlaceholder: 'e.g. Lactose-free milk', saving: 'Saving...', submit: 'Create breakfast plan' },
      dashboard: { eyebrow: 'CASH & REPORTS', title: 'Cash overview', subtitle: 'OWN orders are separated from revenue and kept in their own balance.', filtersLabel: 'Report filters', periods: { day: 'Daily', week: 'Weekly', month: 'Monthly', custom: 'Custom range' }, month: 'Month', day: 'Day', weekDay: 'Day of week', start: 'Start', end: 'End', loading: 'Loading cash data...', loadError: 'Cash data could not be loaded.', deliveredOrders: 'Delivered orders', revenue: 'Total revenue', cost: 'Total cost', profit: 'Net profit', ownBalance: 'OWN balance', ownMeta: '{{count}} OWN order(s) · excluded from revenue', historyTitle: 'Filtered order history', historyNote: 'History records are never deleted', table: { room: 'Room', products: 'Products', payment: 'Payment', amount: 'Amount', deliveredAt: 'Delivered at' }, emptyHistory: 'No delivered orders in this date range.' },
    },
  },
  de: {
    adminOperations: {
      common: { liveOperation: 'LIVE-BETRIEB', breakfastOperation: 'FRÜHSTÜCKSBETRIEB', refresh: 'Aktualisieren', processing: 'Wird bearbeitet...', delivered: 'Ausgeliefert', cancel: 'Abbrechen', save: 'Speichern', room: 'Zimmer', roomValue: 'Zimmer {{number}}', roomUpper: 'ZIMMER', internalAccount: 'INTERNES KONTO', noGuestNote: 'Keine Gastnotiz vorhanden.', note: 'NOTIZ', person: 'Personen', cash: 'Bar', card: 'Kreditkarte', own: 'OWN', optional: 'Optional' },
      orders: { title: 'Offene Bestellungen', subtitle: 'Gästebestellungen werden nach Zimmernummer aufgelistet.', loading: 'Bestellungen werden geladen...', refreshed: 'Bestellliste aktualisiert.', loadError: 'Bestellungen konnten nicht geladen werden.', newItems: '{{count}} neue Bestellung(en) eingegangen.', deliveredToast: 'Bestellung für {{room}} ausgeliefert.', deliverError: 'Die Auslieferung konnte nicht abgeschlossen werden.', cancelAction: 'Stornieren', cancelledToast: 'Bestellung für {{room}} storniert.', cancelError: 'Die Bestellung konnte nicht storniert werden.', emptyTitle: 'Keine offenen Bestellungen', emptyBody: 'Neue Bestellungen erscheinen hier.', closeDialog: 'Dialog schließen', cancelEyebrow: 'BESTELLUNG STORNIEREN', cancelTitle: 'Bestellung für {{room}} stornieren?', cancelWarning: 'Diese Aktion kann nicht rückgängig gemacht werden; die Bestellung bleibt als Stornodatensatz erhalten.', cancelling: 'Wird storniert...', confirmCancel: 'Bestellung stornieren' },
      breakfast: { title: 'Heutige Frühstücke', subtitle: 'Nicht bis 14:00 Uhr ausgelieferte Einträge werden automatisch storniert.', loading: 'Frühstücke werden geladen...', refreshed: 'Frühstücksliste aktualisiert.', loadError: 'Frühstücksliste konnte nicht geladen werden.', newItems: '{{count}} neue Frühstücksanfrage(n).', deliveredToast: 'Frühstück für Zimmer {{room}} ausgeliefert.', deliverError: 'Die Auslieferung konnte nicht abgeschlossen werden.', updated: 'Frühstücksdaten aktualisiert.', updateError: 'Frühstück konnte nicht aktualisiert werden.', edit: 'Bearbeiten', roomNumber: 'Zimmernummer', guestCount: 'Personenzahl', requestedTime: 'Gewünschte Uhrzeit', breakfastDate: 'Frühstücksdatum', emptyTitle: 'Heute keine offenen Frühstücke', emptyBody: 'Geplante Frühstücke erscheinen am Servicetag hier.' },
      createBreakfast: { title: 'Frühstücksplan erstellen', subtitle: 'Beginnen Sie heute oder morgen; pro Aufenthaltstag wird ein Eintrag erstellt.', roomRequired: 'Die Zimmernummer ist erforderlich.', created: '{{count}}-tägiger Frühstücksplan erstellt.', createError: 'Frühstückseintrag konnte nicht erstellt werden.', roomNumber: 'Zimmernummer', roomPlaceholder: 'z. B. 203', guestCount: 'Personenzahl', requestedTime: 'Gewünschte Uhrzeit', startDate: 'Startdatum', breakfastDays: 'Frühstückstage', help: 'Bei 4 Tagen wird für jeden Tag ein eigener Eintrag erstellt, der nur am jeweiligen Servicetag aktiv ist.', guestNote: 'Gastnotiz', notePlaceholder: 'z. B. laktosefreie Milch', saving: 'Wird gespeichert...', submit: 'Frühstücksplan erstellen' },
      dashboard: { eyebrow: 'KASSE & BERICHTE', title: 'Kassenübersicht', subtitle: 'OWN-Bestellungen werden vom Umsatz getrennt in einem eigenen Saldo geführt.', filtersLabel: 'Berichtsfilter', periods: { day: 'Täglich', week: 'Wöchentlich', month: 'Monatlich', custom: 'Eigener Zeitraum' }, month: 'Monat', day: 'Tag', weekDay: 'Wochentag', start: 'Beginn', end: 'Ende', loading: 'Kassendaten werden geladen...', loadError: 'Kassendaten konnten nicht geladen werden.', deliveredOrders: 'Ausgelieferte Bestellungen', revenue: 'Gesamtumsatz', cost: 'Gesamtkosten', profit: 'Nettogewinn', ownBalance: 'OWN-Saldo', ownMeta: '{{count}} OWN-Bestellung(en) · ohne Umsatz', historyTitle: 'Gefilterter Bestellverlauf', historyNote: 'Verlaufsdaten werden nicht gelöscht', table: { room: 'Zimmer', products: 'Produkte', payment: 'Zahlung', amount: 'Betrag', deliveredAt: 'Ausgeliefert um' }, emptyHistory: 'In diesem Zeitraum gibt es keine ausgelieferten Bestellungen.' },
    },
  },
  ar: {
    adminOperations: {
      common: { liveOperation: 'العمليات المباشرة', breakfastOperation: 'عمليات الإفطار', refresh: 'تحديث', processing: 'جارٍ التنفيذ...', delivered: 'تم التسليم', cancel: 'إلغاء', save: 'حفظ', room: 'الغرفة', roomValue: 'الغرفة {{number}}', roomUpper: 'الغرفة', internalAccount: 'حساب داخلي', noGuestNote: 'لم تتم إضافة ملاحظة للضيف.', note: 'ملاحظة', person: 'أشخاص', cash: 'نقداً', card: 'بطاقة ائتمان', own: 'OWN', optional: 'اختياري' },
      orders: { title: 'الطلبات المعلّقة', subtitle: 'تُعرض طلبات الضيوف بحسب رقم الغرفة.', loading: 'جارٍ تحميل الطلبات...', refreshed: 'تم تحديث قائمة الطلبات.', loadError: 'تعذر تحميل الطلبات.', newItems: 'وصل {{count}} طلب جديد.', deliveredToast: 'تم تسليم طلب {{room}}.', deliverError: 'تعذر إتمام التسليم.', cancelAction: 'إلغاء الطلب', cancelledToast: 'تم إلغاء طلب {{room}}.', cancelError: 'تعذر إلغاء الطلب.', emptyTitle: 'لا توجد طلبات معلّقة', emptyBody: 'ستظهر الطلبات الجديدة هنا.', closeDialog: 'إغلاق النافذة', cancelEyebrow: 'إلغاء الطلب', cancelTitle: 'هل تريد إلغاء طلب {{room}}؟', cancelWarning: 'لا يمكن التراجع عن هذا الإجراء؛ سيُحفظ الطلب كسجل إلغاء فقط.', cancelling: 'جارٍ الإلغاء...', confirmCancel: 'إلغاء الطلب' },
      breakfast: { title: 'وجبات إفطار اليوم', subtitle: 'تُلغى تلقائياً السجلات التي لم تُسلّم قبل الساعة 14:00.', loading: 'جارٍ تحميل وجبات الإفطار...', refreshed: 'تم تحديث قائمة الإفطار.', loadError: 'تعذر تحميل قائمة الإفطار.', newItems: 'وصل {{count}} سجل إفطار جديد.', deliveredToast: 'تم تسليم إفطار الغرفة {{room}}.', deliverError: 'تعذر إتمام التسليم.', updated: 'تم تحديث بيانات الإفطار.', updateError: 'تعذر تحديث الإفطار.', edit: 'تعديل', roomNumber: 'رقم الغرفة', guestCount: 'عدد الأشخاص', requestedTime: 'الوقت المطلوب', breakfastDate: 'تاريخ الإفطار', emptyTitle: 'لا توجد وجبات إفطار معلّقة اليوم', emptyBody: 'ستظهر وجبات الإفطار المجدولة هنا في يوم تقديمها.' },
      createBreakfast: { title: 'إنشاء خطة إفطار', subtitle: 'ابدأ اليوم أو غداً؛ يُنشأ سجل لكل يوم من أيام الإقامة.', roomRequired: 'رقم الغرفة مطلوب.', created: 'تم إنشاء خطة إفطار لمدة {{count}} يوم.', createError: 'تعذر إنشاء سجل الإفطار.', roomNumber: 'رقم الغرفة', roomPlaceholder: 'مثال: 203', guestCount: 'عدد الأشخاص', requestedTime: 'الوقت المطلوب', startDate: 'تاريخ البدء', breakfastDays: 'أيام الإفطار', help: 'عند اختيار 4 أيام، يُنشأ سجل مستقل لكل يوم ولا يظهر في القائمة النشطة إلا في يومه.', guestNote: 'ملاحظة الضيف', notePlaceholder: 'مثال: حليب خالٍ من اللاكتوز', saving: 'جارٍ الحفظ...', submit: 'إنشاء خطة الإفطار' },
      dashboard: { eyebrow: 'الصندوق والتقارير', title: 'نظرة عامة على الصندوق', subtitle: 'تُفصل طلبات OWN عن إيرادات الصندوق وتُحفظ في رصيد مستقل.', filtersLabel: 'فلاتر التقرير', periods: { day: 'يومي', week: 'أسبوعي', month: 'شهري', custom: 'نطاق مخصص' }, month: 'الشهر', day: 'اليوم', weekDay: 'يوم الأسبوع', start: 'البداية', end: 'النهاية', loading: 'جارٍ تحميل بيانات الصندوق...', loadError: 'تعذر تحميل بيانات الصندوق.', deliveredOrders: 'الطلبات المسلّمة', revenue: 'إجمالي الإيرادات', cost: 'إجمالي التكلفة', profit: 'صافي الربح', ownBalance: 'رصيد OWN', ownMeta: '{{count}} طلب OWN · خارج الإيرادات', historyTitle: 'سجل الطلبات المفلتر', historyNote: 'لا تُحذف السجلات السابقة', table: { room: 'الغرفة', products: 'المنتجات', payment: 'الدفع', amount: 'المبلغ', deliveredAt: 'وقت التسليم' }, emptyHistory: 'لا توجد طلبات مسلّمة في هذا النطاق الزمني.' },
    },
  },
  ru: {
    adminOperations: {
      common: { liveOperation: 'ТЕКУЩИЕ ОПЕРАЦИИ', breakfastOperation: 'ОПЕРАЦИИ С ЗАВТРАКАМИ', refresh: 'Обновить', processing: 'Обработка...', delivered: 'Доставлено', cancel: 'Отмена', save: 'Сохранить', room: 'Номер', roomValue: 'Номер {{number}}', roomUpper: 'НОМЕР', internalAccount: 'ВНУТРЕННИЙ СЧЁТ', noGuestNote: 'Примечание гостя не указано.', note: 'ПРИМЕЧАНИЕ', person: 'гостей', cash: 'Наличные', card: 'Банковская карта', own: 'OWN', optional: 'Необязательно' },
      orders: { title: 'Ожидающие заказы', subtitle: 'Заказы гостей перечислены по номерам комнат.', loading: 'Загрузка заказов...', refreshed: 'Список заказов обновлён.', loadError: 'Не удалось загрузить заказы.', newItems: 'Поступило новых заказов: {{count}}.', deliveredToast: 'Заказ {{room}} доставлен.', deliverError: 'Не удалось завершить доставку.', cancelAction: 'Отменить', cancelledToast: 'Заказ {{room}} отменён.', cancelError: 'Не удалось отменить заказ.', emptyTitle: 'Нет ожидающих заказов', emptyBody: 'Новые заказы появятся здесь.', closeDialog: 'Закрыть окно', cancelEyebrow: 'ОТМЕНА ЗАКАЗА', cancelTitle: 'Отменить заказ {{room}}?', cancelWarning: 'Это действие нельзя отменить; заказ сохранится только как запись об отмене.', cancelling: 'Отмена...', confirmCancel: 'Отменить заказ' },
      breakfast: { title: 'Завтраки на сегодня', subtitle: 'Записи, не доставленные до 14:00, автоматически отменяются.', loading: 'Загрузка завтраков...', refreshed: 'Список завтраков обновлён.', loadError: 'Не удалось загрузить список завтраков.', newItems: 'Новых записей о завтраке: {{count}}.', deliveredToast: 'Завтрак для номера {{room}} доставлен.', deliverError: 'Не удалось завершить доставку.', updated: 'Данные завтрака обновлены.', updateError: 'Не удалось обновить завтрак.', edit: 'Изменить', roomNumber: 'Номер комнаты', guestCount: 'Количество гостей', requestedTime: 'Желаемое время', breakfastDate: 'Дата завтрака', emptyTitle: 'Сегодня нет ожидающих завтраков', emptyBody: 'Запланированные завтраки появятся здесь в день обслуживания.' },
      createBreakfast: { title: 'Создать план завтраков', subtitle: 'Начните сегодня или завтра; для каждого дня проживания создаётся отдельная запись.', roomRequired: 'Необходимо указать номер комнаты.', created: 'Создан план завтраков на {{count}} дн.', createError: 'Не удалось создать запись о завтраке.', roomNumber: 'Номер комнаты', roomPlaceholder: 'Например, 203', guestCount: 'Количество гостей', requestedTime: 'Желаемое время', startDate: 'Дата начала', breakfastDays: 'Дни завтрака', help: 'Например, при выборе 4 дней создаётся отдельная запись на каждый день, видимая только в день обслуживания.', guestNote: 'Примечание гостя', notePlaceholder: 'Например, безлактозное молоко', saving: 'Сохранение...', submit: 'Создать план завтраков' },
      dashboard: { eyebrow: 'КАССА И ОТЧЁТЫ', title: 'Обзор кассы', subtitle: 'Заказы OWN отделены от выручки и учитываются на отдельном балансе.', filtersLabel: 'Фильтры отчёта', periods: { day: 'День', week: 'Неделя', month: 'Месяц', custom: 'Свой период' }, month: 'Месяц', day: 'День', weekDay: 'День недели', start: 'Начало', end: 'Конец', loading: 'Загрузка данных кассы...', loadError: 'Не удалось загрузить данные кассы.', deliveredOrders: 'Доставленные заказы', revenue: 'Общая выручка', cost: 'Общие затраты', profit: 'Чистая прибыль', ownBalance: 'Баланс OWN', ownMeta: 'Заказов OWN: {{count}} · вне выручки', historyTitle: 'История заказов по фильтру', historyNote: 'Исторические записи не удаляются', table: { room: 'Номер', products: 'Товары', payment: 'Оплата', amount: 'Сумма', deliveredAt: 'Время доставки' }, emptyHistory: 'В этом диапазоне дат нет доставленных заказов.' },
    },
  },
};
